sudo: required
services:
  - docker

before_install:
  - docker build -t shukransozan/docker-react -f Dockerfile.dev .
  
#Series of Comments that run our test suite
script:
  - docker run shukransozan/docker-react npm run test -- -- coverage
  

