sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shukransozan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shukransozan/docker-react npm run test
<<<<<<< HEAD

=======
  
>>>>>>> 70a7f05ad2476e338ddef19da5f5ad8eef34325c
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-739622225748"
  bucket_path: "docker-react"
  on:
    branch: master
<<<<<<< HEAD
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key:
=======
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
>>>>>>> 70a7f05ad2476e338ddef19da5f5ad8eef34325c
      secure: "$AWS_SECRET_KEY"
